<a href="https://colab.research.google.com/github/Th4l3s-pr0g/estudo-IA-CC/blob/main/AlgoritmoGen%C3%A9tico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Passo 1: criar a base de dados que será explorada. No caso, criaremos três arrays: um com os códigos dos produtos, outra com os pesos e outra com os preços dos produtos.

In [15]:
import numpy as np
codProduto = np.arange(1,11)
print("Códigos dos produtos:", codProduto)
peso = np.array([5,8,2,10,7,1,6,20,1,9])
print("Pesos dos produtos:",peso)
preco = np.array([20,440,450,600,900,1000,30,100,500,800])
print("Preços dos produtos:", preco)

print("Cod Produto       Peso      Preço")
for i in range(10):
  print(codProduto[i],"       ", peso[i],"        ", preco[i]) 

Códigos dos produtos: [ 1  2  3  4  5  6  7  8  9 10]
Pesos dos produtos: [ 5  8  2 10  7  1  6 20  1  9]
Preços dos produtos: [  20  440  450  600  900 1000   30  100  500  800]
Cod Produto       Peso      Preço
1         5          20
2         8          440
3         2          450
4         10          600
5         7          900
6         1          1000
7         6          30
8         20          100
9         1          500
10         9          800


Passo 2: uma vez que geramos a base de dados, vamos configurar os parâmetros do algoritmo genético.

1. Definir a capacidade da mochila
2. Definir a quantidade de genes do cromossomo
3. Definir o tamanho da população

In [16]:
capacidadeMochila = 35
tamanhoCadeiaGenetica = 10
tamanhoPopulacao = 5
np.random.seed(2)
populacaoInicial = np.random.randint(0,2, size = (tamanhoPopulacao, tamanhoCadeiaGenetica))
print("População Inicial:\n", populacaoInicial) 

População Inicial:
 [[0 1 1 0 0 1 0 1 0 1]
 [0 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 0 0 0 1 1]
 [1 0 0 1 0 0 1 1 1 0]
 [0 0 0 1 1 1 1 0 0 0]]


Passo 3: uma vez que a população inicial foi gerada, vamos criar uma função para calcular a aptidão de cada cromossomo.

* Se a combinação de produtos do cromossomo NÃO couber na mochila, a aptidão será ZERO.
* Se a combinação COUBER na mochila, a aptidão será a soma dos preços dos produtos contemplados no cromossomo.

In [17]:
def calculaAptidao(populacao):
  aptidao = np.zeros(tamanhoPopulacao)
  #print(aptidao)
  for i in range (tamanhoPopulacao):
    somaPeso = np.sum(populacao[i]*peso)
    if(somaPeso > capacidadeMochila):
      aptidao[i] = 0
    else:
      aptidao[i] = np.sum(populacao[i]*preco)
  return aptidao

In [18]:
aptidaoCalculada = calculaAptidao(populacaoInicial)
print(aptidaoCalculada)

[   0.    0. 3250.    0. 2530.]


Passo 4: Uma vez que sabemos a aptidão de cada cromossomo da população, vamos desenvolver uma função para selecionar os cromossomos para reprodução. No caso, utilizaremos a estratégia elitista, onde os dois cromossomos mais aptos serão selecionados

In [19]:
def selecionaPais(populacao, aptidao):
  numPais = 2
  pais = np.zeros((numPais, tamanhoCadeiaGenetica))
  aptidao_copy = np.copy((aptidao))
  for i in range(numPais):
    posicaoCromossomoMaiorAptidao = np.argmax(aptidao_copy)
    pais[i,:] = populacao[posicaoCromossomoMaiorAptidao,:]
    aptidao_copy[posicaoCromossomoMaiorAptidao] = -1
  return(pais)

In [20]:
pais = selecionaPais(populacaoInicial,aptidaoCalculada)
print(pais)

[[0. 0. 1. 1. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]]


Passo 5: uma vez que os pais foram selecionados para reprodução, é hora de desenvolvermos uma função para fazer o crossover(cruzamento). No nosso caso utilizaremos o cruzamento de um ponto.

In [21]:
def crossover(pais):
  numFilhos = 2

  filhos = np.zeros((numFilhos,tamanhoCadeiaGenetica))

  posicaoCrossover = 3

  filhos[0,posicaoCrossover:] = pais[0,posicaoCrossover:]
  filhos[0,0:posicaoCrossover] = pais[1,0:posicaoCrossover]

  filhos[1,posicaoCrossover:] = pais[1,posicaoCrossover:]
  filhos[1,0:posicaoCrossover] = pais[0,0:posicaoCrossover]

  return filhos

In [22]:
filhos = crossover(pais)
print(filhos)

[[0. 0. 0. 1. 1. 0. 0. 0. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]]


Passo 6: Chegou a hora de desenvolvermos a função que fará a mutação.

In [23]:
import random as rd

def mutacao(filhos):
  txMutacao = 0.2
  posicaoMutacao = int(rd.random() * 10)
  mutantesCandidatos = np.copy(filhos)
  for i in range(2):
    valRandomico = rd.random()
    if valRandomico >= txMutacao:
      print("Filho não sortudo para mutação!")
      continue
    else:
      print("filhos sorteado para mutação!")
      if mutantesCandidatos[i,posicaoMutacao] == 0:
        mutantesCandidatos[i,posicaoMutacao] = 1
      else:
        mutantesCandidatos[i,posicaoMutacao] = 0
  return mutantesCandidatos

In [24]:
mutantes = mutacao(filhos)
mutantes

Filho não sortudo para mutação!
filhos sorteado para mutação!


array([[0., 0., 0., 1., 1., 0., 0., 0., 1., 1.],
       [0., 0., 1., 0., 1., 1., 1., 0., 0., 0.]])

Passo7: para avaliarmos se um filho vai ser parte da população, é necessário criar uma função para calcular a aptidão de cada filho. No nosso caso, criaremos uma função que medirá a aptidão de cada cromossomo individualmente.

In [25]:
def calculaAptidaoIndividual(cromossomo):
  somaPeso = np.sum(cromossomo*peso)
  if somaPeso > capacidadeMochila:
    aptidao = 0
  else:
    aptidao = np.sum(cromossomo*preco)
  return aptidao

In [26]:
calculaAptidaoIndividual(mutantes[1])

2380.0

Ao incluirmos novos membros na população, é coerente que não haja cromossomos iguais.

In [27]:
def inPopulacao(cromossomo, populacao):
  existePopulacao = False
  for element in populacao:
    if np.array_equal(cromossomo, element):
      existePopulacao = True
  return existePopulacao

Passo final: agora que todas as funções necessárias para o algoritmo genético foram  criada, vamos partir para a aplicação da teoria completa. No nosso caso, utilizaremos como critério de parada o número de gerações.

In [28]:
numGeracoes = 1000

populacaoAtual = np.copy(populacaoInicial)

for i in range(numGeracoes):
  #1. Verificar a aptidão de cada cromossomo da população
  aptidaoPopulacao = calculaAptidao(populacaoAtual)
  #2. Uma vez que sabemos a aptidão de cada cromossomo, vamos selecionar 
  # os pais para reprodução
  pais = selecionaPais(populacaoAtual,aptidaoPopulacao)
  #3. Realizar o crossover
  filhos = crossover(pais)
  #4. Verificar se algum filhos será sorteado para mutação
  filhos = mutacao(filhos)

  #5. Agora que os filhos foram gerados, vamos criar uma variável para armazenar
  # a posição do cromossomo de menor aptidão
  posicaoCromossomoMenorAptidao = np.argmin(aptidaoPopulacao)

  #6. Uma vez que armazenamos a posição do cromossomo de menor aptidão, vamos avaliar
  #se algum filho gerado é mais apto do que este cromossomo de menor aptidão.
  if(calculaAptidaoIndividual(filhos[0]) >calculaAptidaoIndividual(populacaoAtual[posicaoCromossomoMenorAptidao])):
      if not inPopulacao(filhos[0], populacaoAtual):
        populacaoAtual[posicaoCromossomoMenorAptidao,:] = filhos[0,:]

  #7. Uma vez que a população pode ter sido alterada em decorrência do filho 0 ser mais
  # apto do que o cromossomo de menor aptidão. É necessário verificar novamente qual
  # cromossomo da população atualizada tem menor aptidão.
  aptidaoPopulacaoAtual = calculaAptidao(populacaoAtual)
  posicaoCromossomoMenorAptidao = np.argmin(aptidaoPopulacaoAtual)

  if(calculaAptidaoIndividual(filhos[1]) >calculaAptidaoIndividual(populacaoAtual[posicaoCromossomoMenorAptidao])):
      if not inPopulacao(filhos[1], populacaoAtual):
        populacaoAtual[posicaoCromossomoMenorAptidao,:] = filhos[1,:]
  
  aptidaoPopulacaoAtual = calculaAptidao(populacaoAtual)
  print("Aptidão dos cromossomos após o crossover", aptidaoPopulacaoAtual)
  print("Cromossomos da população atual: \n", populacaoAtual)
  print("###############################################################")
  print("###############################################################")

A saída de streaming foi truncada nas últimas 5000 linhas.
 [1 0 0 1 1 1 0 0 1 1]
 [0 0 1 1 1 1 0 0 0 1]
 [1 0 1 1 1 1 0 0 1 1]
 [0 0 0 1 1 1 0 0 1 1]]
###############################################################
###############################################################
Filho não sortudo para mutação!
Filho não sortudo para mutação!
Aptidão dos cromossomos após o crossover [4250. 3820. 3750. 4270. 3800.]
Cromossomos da população atual: 
 [[0 0 1 1 1 1 0 0 1 1]
 [1 0 0 1 1 1 0 0 1 1]
 [0 0 1 1 1 1 0 0 0 1]
 [1 0 1 1 1 1 0 0 1 1]
 [0 0 0 1 1 1 0 0 1 1]]
###############################################################
###############################################################
Filho não sortudo para mutação!
Filho não sortudo para mutação!
Aptidão dos cromossomos após o crossover [4250. 3820. 3750. 4270. 3800.]
Cromossomos da população atual: 
 [[0 0 1 1 1 1 0 0 1 1]
 [1 0 0 1 1 1 0 0 1 1]
 [0 0 1 1 1 1 0 0 0 1]
 [1 0 1 1 1 1 0 0 1 1]
 [0 0 0 1 1 1 0 0 1 1]]
##################